language: java
install: ant deps
script:
  - cd prism/prism && make
  - cd ../../yacas && ant jar && mvn install:install-file -Dfile=./dist/lib/yacas.jar -DgroupId=yacas -DartifactId=yacas -Dversion=1.5.0 -Dpackaging=jar
  - cd ../riskexplore && mvn install -q -DskipTests=true
