#!/bin/bash
pat="s#PWD#$(cd ..; pwd)#g"
sed -e "$pat" > rgen <<EOF
#!/bin/sh
docker build -t jdk7 .
docker run -i -v PWD/.m2:/root/.m2 -v PWD/riskexplore:/riskexplore -v PWD/yacas:/yacas jdk7 bash -c "cd /yacas && ant jar && mvn install:install-file -Dfile=./dist/lib/yacas.jar -DgroupId=yacas -DartifactId=yacas -Dversion=1.5.0 -Dpackaging=jar -DlocalRepositoryPath=/root/.m2/repository"
docker run -i -v PWD/.m2:/root/.m2 -v PWD/riskexplore:/riskexplore -v PWD/yacas:/yacas jdk7 bash -c "cd /riskexplore && mvn clean && mvn install"
EOF
chmod +x rgen
export docker=docker
./rgen
